development:
  clients:
    default:
      database: library_exercise_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: library_exercise_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: mongoid_rails_production
      hosts: ["<%= ENV['MONGODB_ADDRESS']%>:27017"]
